### ISSUE TITLE
entering Greek characters on INPUT echoes gibberish

### ISSUE THREAD

**Issue by ianatha** [ianatha/bababasic#60]
<img width="434" alt="Screenshot 2023-11-05 at 2 54 01 AM" src="https://github.com/ianatha/bababasic/assets/38443/d1bc3591-0f59-430d-a90e-d9bc3ff27cea">

**Comment by OpossumPetya** [comment]
same with Russian (2 ASCII chars of that represent one unicode char are printed) and when you try to delete them with backspace itdeletesone extra character

**Comment by ianatha** [comment]
@OpossumPetya thank you for the feedback, this is very valuable! I'll ping you here when I get to fixing this.

**Comment by ianatha** [comment]
@OpossumPetya: v1.2 (102) should fix this issue.

It's going through review on Play Store now -- should be live in less than an hour. The app should prompt you to update on launch.

If by any chance you continue to experience this bug, could you please let me know which Android version you're on?

**Comment by OpossumPetya** [comment]
@ianatha works great now 👍
